name: form_bloc
description: Form bloc package for dart bloc.
version: 0.0.3
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  bloc: ^8.0.4
  equatable: ^2.0.3
